const constants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILED: "LOGIN_FAILED",

  REGISTRATION_SUCCESS: "REGISTRATION_SUCCESS",
  REGISTRATION_FAILED: "REGISTRATION_FAILED",

  VERIFICATION_SUCCESS: "VERIFICATION_SUCCESS",
  VERIFICATION_FAILED: "VERIFICATION_FAILED",

  LOGOUT: "LOGOUT",
}
export default constants
